config:
  checkpoint_freq: 50000
  env_params:
    max_episode_steps: 1000
    reward_type: speed
    target_velocity: 0.5
    time_step: 0.01
  eval_freq: 10000
  log_interval: 10
  n_envs: 4
  n_eval_episodes: 10
  normalize: true
  ppo_params:
    batch_size: 64
    clip_range: 0.2
    clip_range_vf: null
    ent_coef: 0.01
    gae_lambda: 0.95
    gamma: 0.99
    learning_rate: 0.0003
    max_grad_norm: 0.5
    n_epochs: 10
    n_steps: 2048
    policy_kwargs:
      activation_fn: !!python/name:torch.nn.modules.activation.ReLU ''
      net_arch:
      - 256
      - 256
    sde_sample_freq: -1
    target_kl: null
    use_sde: false
    verbose: 1
    vf_coef: 0.5
  render: false
  total_timesteps: 1000000
mean_reward: 10.917550600000002
seed: 42
std_reward: 2.130727575305638e-06
total_timesteps: 1000000
